const app=document.querySelector('#app');let works=[],filter='Alle',query='',current=0,scale=1,tx=0,ty=0,drag=null,pinch=null;
const fav=new Set(JSON.parse(localStorage.getItem('ma-fav')||'[]'));const read=new Set(JSON.parse(localStorage.getItem('ma-read')||'[]'));
const save=()=>{localStorage.setItem('ma-fav',JSON.stringify([...fav]));localStorage.setItem('ma-read',JSON.stringify([...read]));};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function init(){works=await fetch('artworks.json').then(r=>r.json());home();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js?v=8').catch(()=>{})}
function shown(){return works.filter(w=>{if(filter==='Favoriten'&&!fav.has(w.id))return false;if(filter==='Gelesen'&&!read.has(w.id))return false;if(!['Alle','Favoriten','Gelesen'].includes(filter)&&w.museum!==filter)return false;return(`${w.artist} ${w.title} ${w.page}`).toLowerCase().includes(query.toLowerCase())})}
function home(){const list=shown(),last=+(localStorage.getItem('ma-last')||1),next=works.find(w=>w.id===last)||works[0],pct=Math.round(read.size/52*100);
app.innerHTML=`<div class="shell"><header class="hero"><div class="eyebrow">Dein persönlicher Kunstbegleiter</div><h1>Monas Augen</h1><p>52 Werke zum schnellen Nachschauen, Vergrößern und Weiterlesen.</p><button class="maker" data-profile>Gebaut von <b>Jacq990</b> · Profil & Datenschutz</button><div class="continue"><div><small>Weiterlesen bei</small><br><b>${next.id}. ${esc(next.artist)}</b></div><button data-open="${next.id}">Öffnen</button></div><div class="progress"><i style="width:${pct}%"></i></div></header></div><div class="toolbar"><div class="shell"><input class="search" placeholder="Künstler, Werk oder Buchseite suchen" value="${esc(query)}"><div class="filters">${['Alle','Louvre','Musée d’Orsay','Centre Pompidou','Favoriten','Gelesen'].map(x=>`<button data-filter="${x}" class="${x===filter?'active':''}">${x}</button>`).join('')}</div></div></div><main class="shell">${renderGroups(list)}${profileTeaser()}</main>`;
document.querySelector('.search').oninput=e=>{query=e.target.value;home()};document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;home()});document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openWork(+b.dataset.open));document.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>openWork(+b.dataset.card));document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=profile);document.querySelectorAll('[data-heart]').forEach(b=>b.onclick=e=>{e.stopPropagation();const id=+b.dataset.heart;fav.has(id)?fav.delete(id):fav.add(id);save();home()})}
function renderGroups(list){if(!list.length)return'<div class="empty">Keine passenden Werke gefunden.</div>';let groups=[...new Set(list.map(w=>w.museum))];return groups.map(m=>`<section class="section"><h2>${m}</h2><div class="grid">${list.filter(w=>w.museum===m).map(card).join('')}</div></section>`).join('')}
function profileTeaser(){return`<section class="profile-teaser"><div><small>Profil</small><h2>Gebaut von Jacq990</h2><p>Persönlicher Kunstbegleiter ohne Login, Werbung oder Tracking.</p></div><button data-profile>Profil & Datenschutz öffnen</button></section>`}
function card(w){return`<article class="card" data-card="${w.id}"><div class="cover"><img src="${w.image}" alt="${esc(w.title)}"><span class="badge">Werk ${w.id} · Seite ${w.page}</span><button class="heart" data-heart="${w.id}">${fav.has(w.id)?'♥':'♡'}</button></div><div class="body"><div class="meta">${read.has(w.id)?'Gelesen · ':''}${esc(w.museum)}</div><h3>${esc(w.artist)}</h3><div class="title">${esc(w.title)}</div><div class="motto">„${esc(w.motto)}“</div></div></article>`}
function openWork(id){current=works.findIndex(w=>w.id===id);localStorage.setItem('ma-last',id);detail()}
function profile(){app.innerHTML=`<main class="shell detail profile-page"><div class="top"><button id="back">← Galerie</button></div><section class="profile-hero"><div class="eyebrow">Profil</div><h1>Gebaut von Jacq990</h1><p>Monas Augen ist ein persönlicher Kunstbegleiter für 52 Werke aus Louvre, Musée d’Orsay und Centre Pompidou.</p></section><section class="privacy-box"><h2>Datenschutz in Kurzform</h2><ul class="privacy-list"><li><b>Kein Login.</b> Du musst kein Konto anlegen und keine persönlichen Daten eingeben.</li><li><b>Keine Werbung, kein Tracking.</b> Diese App enthält keine eigenen Analyse- oder Werbedienste.</li><li><b>Nur auf deinem Gerät.</b> Favoriten, Lesestatus und Notizen werden im Browser-Speicher deines Geräts abgelegt.</li><li><b>Du hast Kontrolle.</b> Diese lokalen Daten kannst du jederzeit über die Browserdaten deines Geräts löschen.</li></ul><h2>DSGVO- und AV-Hinweis</h2><p>Die App ist datenschutzsparsam aufgebaut und verarbeitet selbst keine Besucherprofile, keine Nutzerkonten und keine Formulareingaben auf einem eigenen Server.</p><p>Die technische Auslieferung erfolgt über GitHub Pages. Laut GitHub Pages Dokumentation kann GitHub beim Besuch einer Pages-Webseite die IP-Adresse aus Sicherheitsgründen protokollieren. Dafür gelten die Datenschutzinformationen von GitHub.</p><p class="fineprint">Dieser Hinweis schafft Transparenz, ersetzt aber keine Rechtsberatung und keine formale Datenschutz- oder AVV-Prüfung.</p><div class="legal-links"><a href="https://docs.github.com/en/pages/getting-started-with-github-pages/what-is-github-pages#data-collection" target="_blank" rel="noopener">GitHub Pages: Data collection</a><a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement" target="_blank" rel="noopener">GitHub Privacy Statement</a></div></section></main>`;document.querySelector('#back').onclick=home}
function detail(){resetZoom();const w=works[current];app.innerHTML=`<main class="shell detail"><div class="top"><button id="back">← Galerie</button><button id="fav">${fav.has(w.id)?'♥':'♡'}</button></div><div class="viewer" id="viewer"><img id="zoomimg" src="${w.image}" alt="${esc(w.title)}"></div><div class="controls"><button id="minus">−</button><button id="plus">+</button><button id="reset">Zurücksetzen</button></div><div class="nav"><button id="prev">← Voriges Werk</button><button id="next">Nächstes Werk →</button></div><div class="meta">${esc(w.museum)} · Werk ${w.id} von 52 · Buchseite ${w.page}</div><h1>${esc(w.artist)}</h1><h2>${esc(w.title)}</h2><blockquote>„${esc(w.motto)}“</blockquote><label class="read"><input id="read" type="checkbox" ${read.has(w.id)?'checked':''}> Dieses Werk habe ich gelesen</label><p class="hint">Tipp: Tippe zweimal auf das Bild oder ziehe es mit zwei Fingern auseinander. Achte zuerst auf die Gesamtwirkung und danach auf Licht, Farbe, Blickrichtung und kleine Details.</p><h3>Meine Notizen</h3><textarea id="note" placeholder="Was fällt dir beim Lesen auf?">${esc(localStorage.getItem('ma-note-'+w.id)||'')}</textarea><div class="status" id="status"></div></main>`;
document.querySelector('#back').onclick=home;document.querySelector('#fav').onclick=()=>{fav.has(w.id)?fav.delete(w.id):fav.add(w.id);save();detail()};document.querySelector('#read').onchange=e=>{e.target.checked?read.add(w.id):read.delete(w.id);save()};document.querySelector('#note').oninput=e=>{localStorage.setItem('ma-note-'+w.id,e.target.value);document.querySelector('#status').textContent='Gespeichert'};document.querySelector('#prev').onclick=()=>{current=(current+works.length-1)%works.length;localStorage.setItem('ma-last',works[current].id);detail()};document.querySelector('#next').onclick=()=>{current=(current+1)%works.length;localStorage.setItem('ma-last',works[current].id);detail()};['plus','minus','reset'].forEach(id=>document.querySelector('#'+id).onclick=()=>zoom(id));setupZoom()}
function resetZoom(){scale=1;tx=0;ty=0;drag=null;pinch=null}function apply(){const i=document.querySelector('#zoomimg');if(i)i.style.transform=`translate(${tx}px,${ty}px) scale(${scale})`}function zoom(id){if(id==='plus')scale=Math.min(6,scale+.3);if(id==='minus'){scale=Math.max(1,scale-.3);if(scale===1)tx=ty=0}if(id==='reset')resetZoom();apply()}
function setupZoom(){const v=document.querySelector('#viewer'),p=new Map();apply();v.onpointerdown=e=>{p.set(e.pointerId,{x:e.clientX,y:e.clientY});v.setPointerCapture(e.pointerId);if(p.size===1)drag={x:e.clientX,y:e.clientY};if(p.size===2){const a=[...p.values()];pinch={d:Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y),s:scale}}};v.onpointermove=e=>{if(!p.has(e.pointerId))return;p.set(e.pointerId,{x:e.clientX,y:e.clientY});if(p.size===2){const a=[...p.values()],d=Math.hypot(a[0].x-a[1].x,a[0].y-a[1].y);scale=Math.max(1,Math.min(6,pinch.s*d/pinch.d));apply();return}if(drag&&scale>1){tx+=e.clientX-drag.x;ty+=e.clientY-drag.y;drag={x:e.clientX,y:e.clientY};apply()}};const end=e=>{p.delete(e.pointerId);drag=null;if(p.size<2)pinch=null};v.onpointerup=v.onpointercancel=end;v.ondblclick=()=>{scale=scale===1?2.3:1;if(scale===1)tx=ty=0;apply()}}
init();
